= Telegram Bot Spring dmi.dk wheater

This Telegram bot can be used to get the weather forecast graphs for your desired city from www.dmi.dk.

== How to use this Telegram Bot

This bot can be used by clicking on *telegram.me/dmi_weather_bot* or *@dmi_weather_bot* in your telegram app.
After doing this you'll get a description of the bot and can directly start using it and send commands.

More information concerning Telegram Bots can be found here: https://core.telegram.org/bots

== Reasons for using this Telegram Bot

Personally I really like the clearly represented weather forecast graphs, which are provided by www.dmi.dk, but on a mobile device they are not easy to reach with the browser and I am not pleased by current apps for this service.
So by implementing this bot I got the chance to really get the raw graphs, which *saves* my *time*, system *resources* on my mobile device and *data volume* from my mobile provider. 

== Tutorial

=== Creating a new Telegram Bot

In order to create a new bot you have to talk with @BotFather. There you can use several commands to create and configure your own bot.

Sending `/help` to the @BotFather gives an overview about the commands.
To create a new bot the `/newbot` command can be used.

=== Provide the api token of your bot

The _bot.dmiweather.token_ property in the _weatherbot.properties_ file should contain token of your bot.

=== Starting the Spring Cloud application

Please make sure you started the telegram-bot-eureka and the telegram-bot-dispatcher applications from https://github.com/SimonScholz/telegram-bot-spring-dispatcher/tree/master/backend first.

Then you can either import the project into the Spring Tool Suite (https://spring.io/tools/sts/all) by using the Buildship(https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md) import wizard and start it from the IDE or simply start the application by running the `bootRun` Gradle task.

[source, console]
----
./gradlew bootRun
----

=== Use the Application

Once the application is running either from the IDE or with Gradle you can test it by navigating to http://localhost:8433/poll, which is used to poll your messages/commands.

Currently 3 commands are supported:

* /now {City name} - Get the current day overview image from dmi.dk
* /week {City name} - Get the week overview image from dmi.dk
* Simply send your location to the bot (in groups this only works in https://core.telegram.org/bots#privacy-mode[private mode] for bots)

When you send one of these commands to your bot and then open http://localhost:8433/poll the Spring Boot application will try to poll your commands and send appropriate answers to the chat with your bot.

By invoking http://localhost:8433/printUpdates it will print the new texts, which are send to the bot.

=== Using long polling

The `de.simonscholz.bot.telegram.PollBot` class registers a long polling process, which is invoked every 10 seconds.
By default the `PollBot` is disabled. To enable it the _poll_ profile has to be activated, e.g., by adding _"poll"_ to the _spring:profiles:active_ property in the _application.yml file.

[NOTE]
====
Long polling should only be used in case it is not possible to provide an ssl webhook endpoint.
====

== Testing the dmi weather bot with curl

In order to test the bot you can send the following JSON to the dispatcher (http://localhost:8080/bot/dmiWebhook), which forwards the `Update` to the dmi weather bot.


[IMPORTANT]
====
In production you want to run the dispatcher on port 443 or 8443 and ssl secure it so that telegram really talks with it.
====


[source, console]
----
curl -H "Content-Type: application/json" -X POST -d '{"update_id":463166625, "message":{"message_id":256,"from":{"id":***my id***,"is_bot":false,"first_name":"Simon","last_name":"S","language_code":"en-US"},"chat":{"id":*** the chat id ***,"first_name":"Simon","last_name":"S","type":"private"},"date":1519229850,"text":"/now Hamburg","entities":[{"offset":0,"length":4,"type":"bot_command"}]}}' http://localhost:8080/bot/dmiWebhook
----


[CAUTION]
====
 *** the chat id*** variable in the curl command must be the chat id of your chat with your bot so that you get the desired dmi weather image.
====

== Technologies

* Spring Boot 2.0 with Webflux
* Spring Cloud
* Reactive MongoDB
* Lombok
* Reactor IO
* Retrofit
* Gradle

== Questions

Please make use of this bot, share your knowledge and adapt it for your needs. 

== Contributing

Feedback is highly appreciated. You may open issues, send pull requests or simply contact me.

== Sources

https://core.telegram.org/bots/api

